### ISSUE TITLE
Newline is broken on Windows when using Beats snippets

### ISSUE THREAD

**Issue by shodanshok** [Graylog2/graylog-plugin-collector#82]
Creating a Beats snippet which extends on multiple lines does not work on Windows.
For example, the following snippets:
```
winlogbeat:
  event_logs:
  - name: Application
    ignoreolder: 168h
  - name: System
  - name: Security
```

produces (on Windows) the following one-liner:

`winlogbeat:  event_logs:   - name: Application     ignoreolder: 168h   - name: System   - name: Security`

which clearly breaks the Windows client.

Checking the source code, I think the problematic entry is [here:](https://github.com/Graylog2/collector-sidecar/blob/master/backends/beats/winlogbeat/render.go#L43) it should use the platform-specific newline escape rather than hardcoding `\n`
